// Freeze the top-K gate-passing genomes after N generations into dist/data/snapshot.<SYMBOL>.js.
// The forward test replays only these genomes on new bars — no re-evolution after T0.
//
// Usage: node tools/make_snapshot.mjs [--symbol BTCUSDT] [--seed 2026] [--warm 50] [--k 5]

import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { makeSeries } from '../dist/engine/series.js';
import { Evolution } from '../dist/engine/evolution.js';
import { FAMILIES } from '../dist/engine/bot.js';

const args = process.argv.slice(2);
const opt = (name, dflt) => {
  const i = args.indexOf('--' + name);
  return i >= 0 && args[i + 1] !== undefined ? args[i + 1] : dflt;
};
const symbol = opt('symbol', 'BTCUSDT').toUpperCase();
const seed = Math.max(1, parseInt(opt('seed', '2026'), 10) || 2026);
const warm = Math.min(500, Math.max(1, parseInt(opt('warm', '50'), 10) || 50));
const k = Math.min(12, Math.max(1, parseInt(opt('k', '5'), 10) || 5));

const here = dirname(fileURLToPath(import.meta.url));
const dataDir = join(here, '..', 'dist', 'data');
const { CANDLES, META } = await import(pathToFileURL(join(dataDir, `candles.${symbol}.js`)).href);

const s = makeSeries(CANDLES);
const evo = new Evolution(s, { seed });
for (let g = 0; g < warm; g++) evo.step();

const passed = evo.pop.filter((x) => x.pass); // pop is ranked by train fitness
// species-diverse cohort: best gate-passer of each family first, then fill by rank
const cohort = [];
const seen = new Set();
for (const x of passed) {
  if (cohort.length >= k) break;
  if (seen.has(x.genome.family)) continue;
  seen.add(x.genome.family);
  cohort.push(x);
}
for (const x of passed) {
  if (cohort.length >= k) break;
  if (!cohort.includes(x)) cohort.push(x);
}
if (cohort.length < k) {
  for (const x of evo.pop) {
    if (cohort.length >= k) break;
    if (!cohort.includes(x)) cohort.push(x);
  }
}
if (!cohort.length) throw new Error('empty population');

const snapshot = {
  version: 1,
  createdAt: new Date().toISOString(),
  seed,
  warm,
  gen: evo.gen,
  symbol: META.symbol,
  interval: META.interval,
  // first forward bar: the hour after the bundled tape ends — nothing after this was seen by evolution
  forwardFrom: META.to + 3600,
  bundledTo: META.to,
  warmupBars: 220,
  gatePassed: passed.length,
  survivors: cohort.map((x) => ({
    id: x.id,
    gen: x.gen,
    family: FAMILIES[x.genome.family],
    genome: x.genome,
    train: x.train,
    val: x.val,
    fit: x.fit,
    pass: x.pass,
  })),
};

const out = join(dataDir, `snapshot.${symbol}.js`);
writeFileSync(
  out,
  '// Generated by tools/make_snapshot.mjs. Frozen cohort for the forward test — do not edit by hand.\n' +
    `export const SNAPSHOT = ${JSON.stringify(snapshot, null, 2)};\n`,
  'utf8',
);
console.log(
  `${symbol}: wrote ${snapshot.survivors.length} survivors (gen ${snapshot.gen}, seed ${seed}, ` +
    `${passed.length} passed gate) -> ${out}\n  forwardFrom ${new Date(snapshot.forwardFrom * 1000).toISOString()}`,
);
